FROM python:3.11-slim

WORKDIR /app

COPY requirements_scripts.txt .
RUN pip install --no-cache-dir -r requirements_scripts.txt

COPY . .

CMD ["uvicorn", "scripts.api.search_server:app", "--host", "0.0.0.0", "--port", "8000"]
